config/routes.rb
Santelmo::Application.routes.draw do
  match 'sitemap.xml' => 'sitemaps#sitemap'
  
  root :to => 'main#index'
  
  get "main/index"
  
  get "main/philosophy"
    
  get "main/menu"
  
  get "main/drinks"
  
  get "main/gaucho"
  
  get "main/reservations"
  
  get "main/events"
  
  get "main/cafe"
  
  get "main/press"
  
  get "main/gallery", :controller => 'main', :action => 'gallery', :as => 'main_gallery'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :load_tweets
  
  def load_tweets
    @tweets = $twitter_client.user_timeline(:count => 1)  # For this demonstration lets keep the tweets limited to the first 5 available.
  end
  
  # cache all pages for 24 hours
  after_filter :cache_action 
  
  def cache_action
    return unless perform_caching
    
    response.headers['Cache-Control'] = 'public, max-age=86400'
    response.headers.delete('cookie')
  end
  
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  N_IMAGES_PER_PAGE = 6
  def gallery
    params[:page] ||= 1
  
    @all_images = [
      {:title => "", :url => 'image-1.jpg', :thumbnail_url => 'thumbnail-1.jpg'},
      {:title => "", :url => 'image-2.jpg', :thumbnail_url => 'thumbnail-2.jpg'},
      {:title => "", :url => 'image-3.jpg', :thumbnail_url => 'thumbnail-3.jpg'},
      {:title => "", :url => 'image-4.jpg', :thumbnail_url => 'thumbnail-4.jpg'},
      {:title => "", :url => 'image-5.jpg', :thumbnail_url => 'thumbnail-5.jpg'},
      {:title => "", :url => 'image-6.jpg', :thumbnail_url => 'thumbnail-6.jpg'},
      {:title => "", :url => 'image-7.jpg', :thumbnail_url => 'thumbnail-7.jpg'},
      {:title => "", :url => 'image-8.jpg', :thumbnail_url => 'thumbnail-8.jpg'},
      {:title => "", :url => 'image-9.jpg', :thumbnail_url => 'thumbnail-9.jpg'},
      {:title => "", :url => 'image-10.jpg', :thumbnail_url => 'thumbnail-10.jpg'},
      {:title => "", :url => 'image-11.jpg', :thumbnail_url => 'thumbnail-11.jpg'},
      {:title => "", :url => 'image-12.jpg', :thumbnail_url => 'thumbnail-12.jpg'},
      {:title => "", :url => 'image-13.jpg', :thumbnail_url => 'thumbnail-13.jpg'},
      {:title => "", :url => 'image-14.jpg', :thumbnail_url => 'thumbnail-14.jpg'},
      {:title => "", :url => 'image-15.jpg', :thumbnail_url => 'thumbnail-15.jpg'},
      {:title => "", :url => 'image-16.jpg', :thumbnail_url => 'thumbnail-16.jpg'},
      {:title => "", :url => 'image-17.jpg', :thumbnail_url => 'thumbnail-17.jpg'},
      {:title => "", :url => 'image-18.jpg', :thumbnail_url => 'thumbnail-18.jpg'},
      {:title => "", :url => 'image-19.jpg', :thumbnail_url => 'thumbnail-19.jpg'},
      {:title => "", :url => 'image-20.jpg', :thumbnail_url => 'thumbnail-20.jpg'},
      {:title => "", :url => 'image-21.jpg', :thumbnail_url => 'thumbnail-21.jpg'},
      {:title => "", :url => 'image-22.jpg', :thumbnail_url => 'thumbnail-22.jpg'},
      {:title => "", :url => 'image-23.jpg', :thumbnail_url => 'thumbnail-23.jpg'},
      {:title => "", :url => 'image-24.jpg', :thumbnail_url => 'thumbnail-24.jpg'},
      {:title => "", :url => 'image-25.jpg', :thumbnail_url => 'thumbnail-25.jpg'},
      {:title => "", :url => 'image-26.jpg', :thumbnail_url => 'thumbnail-26.jpg'},
      {:title => "", :url => 'image-27.jpg', :thumbnail_url => 'thumbnail-27.jpg'},
      {:title => "", :url => 'image-28.jpg', :thumbnail_url => 'thumbnail-28.jpg'},
      {:title => "", :url => 'image-29.jpg', :thumbnail_url => 'thumbnail-29.jpg'}
    ]
    
    @current_page = params[:page].to_i || 1
    
    @next_page = @current_page + 1
    @next_page = nil if @current_page * N_IMAGES_PER_PAGE >= @all_images.length
    
    @previous_page = @current_page - 1
    @previous_page = nil if @previous_page < 1

    first_image = (@current_page - 1) * N_IMAGES_PER_PAGE
    @images = @all_images[first_image, N_IMAGES_PER_PAGE]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(text, path, current = nil)
    current ||= current_page?(path)
    
    content_tag :div, :class => 'link' + (current ? ' current' : '') do
      link = line_break + link_to(text, path, :class => 'pjax')
      
      link += link_to(main_index_path, :class => 'pjax') do 
        content_tag(:div, "", :class => "active_link cross")
      end 
      
      link
    end
    
  end
  
  def nav_sublink(text, path, current = nil)
    current ||= current_page?(path)
    
    content_tag :div, :class => 'link' + (current ? ' current' : '') do
      link = link_to(text, path, :class => 'pjax')
      
      link += link_to(main_index_path, :class => 'pjax') do 
        content_tag(:div, "", :class => "active_link cross")
      end 
      
      link
    end
    
  end
  
  
  
  def line_break(width = 31)
    content_tag :div, :class => 'line_break' do
      ("&#8226;" * width).html_safe
    end
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/_menu.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div id="menu">
  <div id="menu_wrapper">
    <%= link_to(main_index_path, :class => 'pjax') do %>
      <%= image_tag("logo.png", :size => "200x84 ", :alt => "San Telmo Logo", :id => 'logo') %>
    <% end %>
    <div id="nav">
      <%= nav_link 'Philosophy', main_philosophy_path %>
      <%= nav_link 'Menu', main_menu_path %>
      <%= nav_link 'Drinks', main_drinks_path %>
      <%= nav_link 'Reservations', main_reservations_path %>
      <%= nav_link 'Gallery', main_gallery_path(:page => 1), params[:action] == 'gallery' %>
      <%= nav_link 'Press', main_press_path %>
      <%= nav_link 'Employment', main_employment_path %>
      <%= line_break %>
    </div>
    <div id="footer">
      <%= render 'layouts/tweets' %>
      <%= link_to("https://twitter.com/San_Telmo_", :id => 'tweet_link') do %>
        <div id="twitter" class="social"></div>
      <% end %>
      <%= link_to("https://www.facebook.com/pages/San-Telmo/238471602841880") do %>
        <div id="facebook" class="social"></div>
      <% end %>
      <br>
      <%= line_break %>
      <p>
        8am - late Mon to Friday<br />
        12pm - late Sat & Sun
      </p>
      <p>
        Phone: +61 (3) 9650 5525<br />
        Fax: +61 (3) 9650 5526
      </p>
      <%= link_to(main_reservations_path, :class => 'pjax') do %>
        <p>
          14 Meyers Pl, Melbourne 3000<br/>
          BTW Bourke & Lt Collins Sts
        </p>
      <% end %>
      <a href="mailto:info@santelmo.com.au">info@santelmo.com.au</a>
      <%= line_break %>
    </div>
  </div>
</div>

app/views/layouts/_tweets.html.erb
<section id="tweets">
    <% @tweets.each do |tweet| %>
      <%= link_to tweet.full_text, "#{tweet.url}", class: "twitter_link", target: "_blank" %><br>
      <i>- <%= tweet.created_at.to_formatted_s(:day_and_month) %></i>
    <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>San Telmo - Argentinian Bar and Restaurant, Melbourne</title>
  <meta name="description" content="San Telmo is a new and exciting restaurant and bar, inspired by not only a love of Argentinian food and wine, but also Argentinian’s vivacious lifestyle and rich culture." />
  <meta name="keywords" content="argentinian, latin food, steak, san telmo, restaurant, melbourne, CBD, beef, bbq, wine, south america" />
  <%= stylesheet_link_tag :application %>
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tags %>
  <link href="http://fonts.googleapis.com/css?family=Kreon" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet" type="text/css">
  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-26630071-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

  </script>
</head>
<body>
  <%= render 'layouts/menu' %>
  <div id="bg">
    <%= yield %>
  </div>
</body>

</html>

app/views/main/cafe.html.erb
<div class="right_float" id="main">
  <%= link_to(main_index_path, :id => 'close_page', :class => 'pjax cross') do %>
  <% end %>
  <h1>Cafe San Telmo</h1>
  <%= line_break(70) %>
  <%= image_tag ("cafe-san-telmo.png"), size: "330x167", class: "center", alt: "The Cafe San Telmo menu" %>
  <p class="abstract">Cafe San Telmo is open for coffee and a light breakfast Monday - Friday from 8am until 11.30am.</p>
  <div class="page_break"></div>

  <div id="menu-wrapper">
    <div class="menu-links">
      <%= link_to('/assets/cafe-san-telmo-placemat.pdf', :target => '_blank') do %>
        <!-- <i class="fa fa-download"></i> -->
        <%= image_tag("cafe-san-telmo-placemat.jpg", :size => "460x325 ", :alt => "Cafe San Telmo Placemat") %>
      <% end %>
    </div>  
  </div>
  <p>Enter through Windsor Place to enjoy 5 Senses Coffee made by our dedicated barista, alongside our house baked Argentinian treats or an antioxidant rich blend of Brazilian super fruit Acai.</p>
  <p>Don't miss out on our early bird coffee, $3 between 8am and 9am.</p>
  <div id="spacer"></div>
</div>

app/views/main/drinks.html.erb
<div class="right_float" id="main">
  <%= link_to(main_index_path, :id => 'close_page', :class => 'pjax cross') do %>
  <% end %>
  <h1>Drinks</h1>
  <%= line_break(70) %>
  <p class="abstract">We offer an all-Argentinian wine list and exclusive Argentine beers hand-selected by the restaurateurs during their adventures. You can enjoy an exciting range of beverages ranging from a glass (or bottle) of malbec or torrontes, an an Argentinian craft beer, a Fernet Branca and cola or a pisco sour.</p>
  <p class="abstract">Our cocktail list offers a selection of drinks inspired by Santiago Policastro, or “Pichin”, Buenos Aires’ most distinguished bartender in the 1930s and 1940s and other modern cocktails popular in Latin America today.</p>
  <div class="page_break"></div>
  <h3>About Argentinian wine</h3>
  <%= link_to('http://dl.dropbox.com/u/7697218/menu/drinks_menu.pdf', :target => '_blank') do %>
    <div id="drinks_link"></div>
  <% end %>
  <p>With a rich wine history of over 500 years experience, coupled with the investment and influence of top wine producers from Spain, Italy and France, Argentinian wine has greatly improved in quality and is finally receiving the recognition it deserves as the world's fifth largest wine producer.</p>
  <p>Mendoza sets itself apart from other wine regions with its proximity to the Andes providing purity of environment, intense light and a harsher climate through which the grapes are forced to struggle, creating an interesting and natural fruit driven palate. From Salta and Cafayate in the north, down to Patagonia and the Rio Negro in the south, we have sourced our wines to represent all different regions and climates in Argentina.</p>
  <p>Many of our wines are personally sourced and only available at San Telmo.</p>
  <div id="spacer"></div>
</div>

app/views/main/employment.html.erb
<div class="right_float" id="main">
  <%= link_to(main_index_path, :id => 'close_page', :class => 'pjax cross') do %>
  <% end %>
  <h1>Employment</h1>
  <%= line_break(70) %>
  <p class="abstract"><em>"Vení a San Telmo"</em></p>
  <p class="abstract">Our people are the most important part of San Telmo and we are committed to developing a team through ongoing personal development and training. We work hard, we learn about Argentine cuisine, wine and culture and we have fun doing it.</p>
  <div class="page_break"></div>
  <div id="staff"></div>
  <h2>Join San Telmo's Kitchen Team</h2>
  <p>Our imported 2.5 metre charcoal grill, known in Argentina as a parrilla, is barbecue paradise with people travelling from all around to see the magic happening over the hot coals.</p>
  <p>You will learn to display your skills in our open kitchen with the close guidance and mentoring of Mike Patrick (head chef) and Glenn Ellett (sous chef). Using top local produce and the latest kitchen equipment you will learn about South American cuisine and culture. Experience in an open kitchen and direct contact with customers form a fundamental part of the lively culture and atmosphere of the restaurant, improving your people skills and the vibe of the kitchen.</p>
  <p>We appreciate the importance of a work/life balance and provide flexible working hours that can be tailored to meet family and social needs. For the right applicant we offer extensive management training in a positive work environment, with opportunity for career progression.</p>
  <p>The applicant we are looking for will be motivated and passionate about food and their career in restaurants with a positive “can do” attitude. They must be punctual, hardworking and committed to learn and develop with San Telmo.</p>
  <p>Please send your CV and expression of interest to <%= mail_to "info@santelmo.com.au" %></p>
  <h2>Join our Floor and Bar Team</h2>
  <p>We are always open to applications from committed and motivated floor and bar staff who are interested in learning and growing with the San Telmo team.</p>
  <p>We have the only exclusively Argentinian wine list in the Australia and provide ongoing training about the Argentine wine regions and styles from specialist winemakers in the region) as well as Argentine food and culture.</p>
  <p>We offer a fun and lively work environment with flexible hours and attainable rewards, with in house and exterior management training for the right people. Our aim is to help develop staffs skills to maximise their potential and grow within the business.</p>
  <p>The right candidates will be committed, have exceptional customer (and kitchen) interaction skills and be ready to embrace the culture of San Telmo and the Argentine ethos: <em>“eating, drinking and most importantly living are there to be enjoyed with friends and family”</em></p>
  <p>If this is you then send your CV and an expression of interest to <%= mail_to "info@santelmo.com.au" %></p>
  <div id="spacer"></div>
</div>

app/views/main/events.html.erb
<div class="right_float" id="main">
  <%= link_to(main_index_path, :id => 'close_page', :class => 'pjax cross') do %>
  <% end %>
  <h1>What's On'</h1>
  <%= line_break(70) %>
  <ul class="events">
    <li>
      <%= image_tag ("gaucho.png"), size: "400x270", alt: "Gaucho promotional photo" %>
      <h2>Gaucho Lunch</h2>
      <p>Gaucho lunch $40 per person including two courses, a glass of wine and tea or coffee.</p>
    </li>
    <li>
      <%= image_tag("events/san-telmo-gnocchi-day.jpg", :size => "450x250", :alt => "Gnocchi Day Banner") %>
      <h2>Gnocchi Day</h2>
      <p>San Telmo invites you to celebrate Dia de Noquis (Gnocchi Day) on Monday September 30.</p>
      <%= link_to "Read more…", "http://link.restaurantdiary.com.au/v/443/f36b478f79684b96eb9e6fbaa0246b9d7b705c7b49f670da", :target => '_blank' %>
    </li>
    <div class="page_break"></div>
    <li>
      <%= image_tag("events/san-telmo-spring-roast.jpg", :size => "450x250", :alt => "Sunday Asado Banner") %>
      <h2>Sunday Asado</h2>
      <p>Every Sunday at San Telmo we take an Argentinian approach to the traditional Sunday roast, with delicious meat slow roasted on our Parrilla, served with chimichurri and perfectly matched with a class of malbec.</p>
      <%= link_to "Read more…", "http://link.restaurantdiary.com.au/v/443/f36b478f79684b96ec272ca962de0f2c7b705c7b49f670da", :target => '_blank' %>
    </li>
  </ul>  
  <div id="spacer"></div>
</div>

app/views/main/gallery.html.erb
<div class="full_page" id="main">
  <div id="gallery_wrapper">
    <%= link_to({:page => @next_page}, :class => 'pjax' + (@next_page.nil? ? ' hidden' : '')) do %>
      <div id="arrow_right"><p>Next</p></div>
    <% end %>
    <%= link_to({:page => @previous_page}, :class => 'pjax' + (@previous_page.nil? ? ' hidden' : '')) do %>
      <div id="arrow_left"><p>Prev</p></div>
    <% end%>
    
    <h1>Gallery</h1>
    <%= line_break(160) %>
    <% @images.each do |image| %>
      <a class="lightbox" href="/assets/gallery/<%= image[:url] %>" title="<%= image[:title] %>">
        <img class="thumbnail" src="/assets/gallery/<%= image[:thumbnail_url] %>" />
      </a>
    <% end %>
  </div>
</div>

app/views/main/index.html.erb
<div id="ghost-box">
  <div>
    <p><strong>'BIENVENIDOS A SAN TELMO'</strong> - WELCOME TO SAN TELMO</p>
    <p>Inspired by a love of Argentinian food, wine, vivacious lifestyle and rich culture, our menu follows the Agentine tradition of sharing food.</p>
    <p>The Parrilla (imported Argentine charcoal grill) is the focal point of our cuisine, importing a unique flavour to the dishes. We recommend you combine dishes from all sections of our menu to create an experience that can be enjoyed with colleagues, friends and family.</p>
    <p>We look forward to sharing the food, the wine and our memories of Buenos Aired and Argentine with you.</p>
  </div>
</div>

app/views/main/menu.html.erb
<div class="right_float" id="main">
  <%= link_to(main_index_path, :id => 'close_page', :class => 'pjax cross') do %>
  <% end %>
  <h1>Menu</h1>
  <%= line_break(70) %>
  <p class="abstract">Our sharing style menu is inspired by the meals we came to know and love during our time in Argentina. The social element of an asado is an integral part of Argentinian culture and is considered an opportunity to enjoy great food and wine with family and friends. We look forward to sharing our love of the Argentine parrilla (charcoal grill) with you.</p>
  <%= image_tag ("food-image.jpg"), :size => "400x270", class: "center", alt: "Private dining room" %>
  <div class="page_break"></div>
  <div id="menu-wrapper">
    <div class="menu-links">
      <%= link_to('http://dl.dropbox.com/u/7697218/menu/menu.pdf', :target => '_blank') do %>
        <%= image_tag("menu-thumbnail.png", :size => "220x312 ", :alt => "Menu Thumbnail") %>
      <% end %>
    </div>  
    <div class="menu-links">
      <%= link_to('http://dl.dropbox.com/u/7697218/menu/set_menu.pdf', :target => '_blank') do %>
        <%= image_tag("setmenu-thumbnail.png", :size => "220x312 ", :alt => "Menu Thumbnail") %>
      <% end %>
    </div>  
  </div>
  <p>We focus on the simplicity of Argentine cooking, with hearty Argentine favourites including empanadas, entraña (hanger steak), chorizo, morcilla (spiced black sausage) and mollejas (sweetbreads) along with other dishes from the grill.</p>
  <p>We use the highest quality locally raised pasture-fed and free range Hereford and Angus beef. The majority of our beef comes from O’connor’s Premium, the very best beef from Gippsland. All cuts of meat are presented with a recommended cooking degree, however we do accommodate requests for specific cooking preferences.</p>
  <p>There are plenty of vegetarian dishes on offer and we cater for dietary requirements wherever possible. A large selection of side dishes complement the seasons, with favourites such as brócoli (fried broccoli with salted ricotta) and zanahorias (burnt carrots with thyme and goats curd).</p>
  <p>Of course, a meal at San Telmo is not complete without tasting the Argentine national dessert, dulce de leche, which you find in our ever popular flan.</p>
  <div id="spacer"></div>
</div>

app/views/main/philosophy.html.erb
<div class="right_float" id="main">
  <%= link_to(main_index_path, :id => 'close_page', :class => 'pjax cross') do %>
  <% end %>
  <h1>Philosophy</h1>
  <%= line_break(70) %>
  <p class="abstract">Inspired by a love of Argentinian food, wine, vivacious lifestyle and rich culture, San Telmo is a restaurant and bar situated in Meyers Place.</p>
  <p class="abstract">Offering a warm and casual option for breakfast, lunch and dinner, San Telmo follows the Argentinian ethos that eating, drinking and living are best enjoyed with friends, family and lovers.</p>
  <div class="page_break"></div>
  <div id="philosophy_image"></div>
  <p>The name San Telmo originates from the oldest neighbourhood of Buenos Aires, a suburb full of traditional parrilla restaurants, bars and beautiful colonial buildings creating an enchanting backdrop for the eclectic bohemian art and a weekend street market.</p>
  <p>The restaurant’s interior is a meeting of old world Argentine bodega and the open-plan style of Melbourne dining where the kitchen is an intimate part of the atmosphere. The interior is appointed with imported cow hides, 300-year-old antique doors and historic 1930s coloured glass soda siphon bottles from the suburb of San Telmo.</p>
  <p>The kitchen is focussed around our bespoke 2.5 metre parrilla (charcoal grill), hand made for us in Argentina by Pirincho, a lifelong master of the craft. As one of the most highly regarded parrilla craftsman in the world, Pirincho’s previous customers include former Argentine presidents, the Ferrari workshop in Modena, and the VIP restaurant in the Barcelona FC Stadium.</p>
  <p>We look forward to being able to share the food, the wine and our memories of Buenos Aires and Argentina with you.</p>
  <div id="spacer"></div>
</div>

app/views/main/reservations.html.erb
<div class="right_float" id="main">
  <%= link_to(main_index_path, :id => 'close_page', :class => 'pjax cross') do %>
  <% end %>
  <h1>Reservations</h1>
  <%= line_break(70) %>
  <p class="abstract">Yes we do take reservations at San Telmo. 
Bookings are encouraged in advance, however we do keep a number of spaces free for when you do have that last minute urge for a steak and red wine.</p>
  <div class="page_break"></div> 
  <%= image_tag ("food-image.jpg"), :size => "400x270", class: "center", alt: "Private dining room" %>
  <p class="abstract">In our private dinning space we can accommodate groups of 10-14 where we offer different set menu options. With advance notice we can organise an asado animal of your choice to be slow cooked on the parrilla.</p>
  <p class="abstract">A credit card deposit is required to confirm all group bookings of 8 people or more. Contact us directly for more information about large bookings.</p>
  <h2>Call us at the restaurant or book online to make a reservation.</h2>
  <p class="abstract">+61 (3) 9650 5525</p>
  <iframe id="book-online" src="http://cms.dimmi.com.au/Widget/Default.aspx?id=2822&location=http://santelmo.com.au" height="390" width="300" frameborder="0" scrolling="no"></iframe>
  <!-- <a id="book_online" href="javascript:void(window.open('http://cms.dimmi.com.au/Widget/Default.aspx?id=2822&location=http://santelmo.com.au','Dimmi','width=302,height=432,top=60,left=60'))"><img src="http://cms.dimmi.com.au/Images/Restaurants/173.gif" style="border:none;" alt="Book Online"></a> -->
  <div id="spacer"></div>
</div>